export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_DEFINITIONS_SUCCESS = 'GET_DEFINITION_SUCCESS';
export const SET_ACTIVE_MOVIE = 'SET_ACTIVE_MOVIE';
export const SET_ACTIVE_DEFINITION = 'SET_ACTIVE_DEFINITION';
export const START_LOADING = 'START_LOADING';

