export const GET_MOVIES_SUCCESS = 1000;
export const GET_DEFINITIONS_SUCCESS = 1001;
export const SET_ACTIVE_MOVIE = 1002;
export const SET_ACTIVE_DEFINITION = 1003;
export const WORDS_SELECTION_SUCCESS = 1004;
export const SET_ACTIVE_WORD = 1005;
export const SET_ACTIVE_WORD_INDEX = 1006;
export const SET_ACTIVE_DEFINITION_INDEX = 1007;
export const START_LOADING = 1008;

